dist:     bionic
sudo:     required

language: c

os: linux

compiler: gcc

env:
  global:
    - CODECOV_TOKEN="83d8152e-4406-4ced-8d01-5782b464d196"

install:
    - sudo apt-get update
    - sudo apt-get install valgrind
    - sudo apt-get install clang-format
    - sudo apt-get install lcov
    - sudo apt-get install libstdc++6
    - sudo apt-get install cmake
    - sudo apt-get install cppcheck
    # Google tests
    - sudo apt-get install libgtest-dev
    - cd /usr/src/gtest
    - sudo cmake .
    - sudo make
    - sudo cp *.a /usr/lib
    - cd -
    
before_script:
    - ./linters/run.sh --local || travis_terminate 1

script:
    - cmake .
    - make || travis_terminate 1
    - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med  --track-origins=yes ./test_longest_arth_seq.out || travis_terminate 1
    - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med  --track-origins=yes ./test_parse_input.out || travis_terminate 1

after_script:
    - lcov —capture —directory ./CMakeFiles/task_library.dir/project/src —output-file coverage.info
    - bash <(curl -s https://codecov.io/bash)
    - make clean
